swagger: "2.0"
info:
  version: "1.0.0"
  title: SOAJS Demo
host: localhost
basePath: /serviceDemo
schemes:
  - http
paths:
  /user:
    post:
      tags:
        - user
      summary: Create user
      parameters:
        - in: body
          name: user
          description: Created user object
          required: true
          schema:
            $ref: "#/definitions/item"
      responses:
        200:
          description: successful operation
        400:
          description: unsuccessful update
        600:
          description: couldn't establish connection to database
    get:
      tags:
        - user
      summary: get user by id
      parameters:
        - in: query
          name: id
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
        401:
          description: user id not found
        600:
          description: couldn't establish connection to database
    delete:
      tags:
        - user
      summary: delete a user by Id
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: successful operation
        401:
          description: user id not found
        600:
          description: couldn't establish connection to database
    put:
      tags:
        - user
      summary: Update user
      parameters:
        - $ref: "#/parameters/user"
      responses:
        200:
          description: successful operation
        400:
          description: unsuccessful update
        600:
          description: couldn't establish connection to database
parameters:
  id:
    in: query
    name: id
    required: true
    type: integer
    format: int64
  user:
    in: body
    name: user
    description: Created user object
    required: true
    schema:
      $ref: "#/definitions/item"
definitions:
  item:
    type: object
    required: [id, username, email]
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
        minLength: 4
        maxLength: 8
        pattern: /^[a-zA-Z][0-9a-zA-Z_\-]+$/
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: array
        items:
          type: object
          required: [address, primary]
          minItems: 1
          maxItems: 6
          uniqueItems: true
          properties:
            address:
              type: string
              format: email
            primary:
              type: boolean